# Generated by Django 3.1.7 on 2021-04-08 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('_id', models.CharField(max_length=200)),
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('guid', models.CharField(max_length=200)),
                ('has_died', models.BooleanField(max_length=20)),
                ('balance', models.DecimalField(decimal_places=3, max_digits=10)),
                ('picture', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('eyeColor', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('company_id', models.IntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('about', models.CharField(max_length=100)),
                ('registered', models.DateField(max_length=100)),
                ('tags', models.TextField(null=True)),
                ('friends', models.IntegerField(blank=True, null=True)),
                ('greeting', models.TextField(max_length=300)),
                ('favoriteFoods', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company_Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.people')),
            ],
        ),
    ]
