# Generated by Django 3.1.7 on 2021-04-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_company_staff_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField()),
                ('friends', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
