# Generated by Django 3.1.7 on 2021-04-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_friend_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='about',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='people',
            name='registered',
            field=models.DateField(max_length=200),
        ),
    ]
