# Generated by Django 3.1.7 on 2021-04-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210408_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_staff',
            name='company',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='people',
            name='_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='people',
            name='about',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='people',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='people',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='people',
            name='eyeColor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='people',
            name='guid',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='people',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='people',
            name='picture',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='people',
            name='registered',
            field=models.DateField(max_length=100),
        ),
    ]
