# Generated by Django 3.1.7 on 2021-04-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210408_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='people',
            name='eyeColor',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='people',
            name='guid',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='people',
            name='picture',
            field=models.CharField(max_length=255),
        ),
    ]
