# Generated by Django 3.1.7 on 2021-04-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210408_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_staff',
            name='company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='people',
            name='about',
            field=models.CharField(max_length=255),
        ),
    ]
