# Generated by Django 3.1.7 on 2021-04-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210408_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='about',
            field=models.CharField(max_length=2000),
        ),
    ]
