# Generated by Django 3.1.7 on 2021-04-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210408_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='balance',
            field=models.FloatField(),
        ),
    ]
