# Generated by Django 3.1.7 on 2021-04-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210409_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='friends',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
